{% set name = "datavzrd" %}
{% set version = "2.58.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/datavzrd/datavzrd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a26e7b8c1befbbd93d654fa2970ab7e3c241d40e7ffddfbb3c12043d2b5ef385

build:
  number: 0
  skip: true  # [win or py<310]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cargo-bundle-licenses
    - nodejs
    - pnpm
    - pkg-config
  host:
    - openssl
    - python
  run:
    - python
    - yte

test:
  commands:
    - datavzrd --help

about:
  home: https://github.com/datavzrd/datavzrd
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A tool to create visual interactive standalone HTML reports from collections of CSV/TSV tables
  description: |
    A tool to create visual and interactive standalone HTML reports from 
    collections of CSV/TSV tables. 
    Reports include automatically generated vega-lite histograms 
    per column. Plots can be fully customized by users via a config file. 
    These also enable the user to add linkouts to other websites or link 
    between multiple tables.
  doc_url: https://github.com/datavzrd/datavzrd
  dev_url: https://github.com/datavzrd/datavzrd

extra:
  recipe-maintainers:
    - johanneskoester
    - fxwiegand
