{% set name = "datavzrd" %}
{% set version = "2.52.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/datavzrd/datavzrd/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3b128ab53d3cd88b550a68dd439ddafc42cae30165dbbea8cbe45b931af94ee2

build:
  number: 0
  # TODO osx-arm64 builds fail (https://github.com/conda-forge/datavzrd-feedstock/pull/153), reenable them once fixed
  skip: true  # [(osx and arm64) or win or py<310]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - nodejs
    - pnpm
    - pkg-config
  host:
    - openssl
    - python
  run:
    - python
    - yte

test:
  commands:
    - datavzrd --help

about:
  home: https://github.com/datavzrd/datavzrd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to create visual interactive standalone HTML reports from collections of CSV/TSV tables
  description: |
    A tool to create visual and interactive standalone HTML reports from 
    collections of CSV/TSV tables. 
    Reports include automatically generated vega-lite histograms 
    per column. Plots can be fully customized by users via a config file. 
    These also enable the user to add linkouts to other websites or link 
    between multiple tables.
  doc_url: https://github.com/datavzrd/datavzrd
  dev_url: https://github.com/datavzrd/datavzrd

extra:
  recipe-maintainers:
    - johanneskoester
    - fxwiegand
